### PR TITLE
Keywords

### PR DESCRIPTION
**Pull request by DavidBriglio**
Added:
- CATCH
- DIALOG
- DYNAMIC
- TRY

### CODE REVIEW

**Comment by INGCRENGIFO** [comment]
Hello, I can not find those reserved words within the Informix 4GL documentation.

**Comment by DavidBriglio** [comment]
Here are some links to the documentation (3.00): 
- [DYNAMIC](http://4js.com/online_documentation/fjs-fgl-3.00.02-manual-html/#c_fgl_Arrays_010.html)
- [TRY/CATCH](http://4js.com/online_documentation/fjs-fgl-3.00.02-manual-html/#c_fgl_Exceptions_007.html)
- [DIALOG](http://4js.com/online_documentation/fjs-fgl-3.00.02-manual-html/#c_fgl_prog_dialogs_the_dialogs.html)

**Comment by DavidBriglio** [comment]
I realize now that there may be differences in the Genero 4GL opposed to Informix. You can close this PR if it does not apply.

**Comment by INGCRENGIFO** [comment]
Now I see that there are many similarities between genre and 4gl, I like the idea that this plugin works for both languages, I will accept this change but will make some modifications, so far as you have been with genre and the Informix 4gl plugin?

**Comment by DavidBriglio** [comment]
I have only been using this with Genero 4GL, and so far it has been working pretty well.

**Comment by INGCRENGIFO** [comment]
perfect, I'm glad it works, in about 4 hours I launch the update.

**Pull request merged**
